/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CollectionJsonld } from './collection-jsonld';


export interface CategoryJsonld { 
    readonly '@context?': string | any | null;
    readonly '@id'?: string;
    readonly '@type'?: string;
    readonly id?: number;
    title?: string;
    description?: string | null;
    products?: Array<string>;
    parent?: string | null;
    readonly id_parent?: Array<string>;
    idParent?: CollectionJsonld;
}

