/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Collection } from './collection';


export interface Category { 
    readonly id?: number;
    title?: string;
    description?: string | null;
    products?: Array<string>;
    parent?: string | null;
    readonly id_parent?: Array<string>;
    idParent?: Collection;
}

