/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserJsonldLightRead } from './user-jsonld-light-read';
import { InlineResponse200HydraView } from './inline-response-200-hydra-view';
import { InlineResponse200HydraSearch } from './inline-response-200-hydra-search';


export interface InlineResponse2005 { 
    'hydra:member': Array<UserJsonldLightRead>;
    'hydra:totalItems'?: number;
    'hydra:view'?: InlineResponse200HydraView;
    'hydra:search'?: InlineResponse200HydraSearch;
}

