/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InlineResponse200HydraSearchHydraMapping } from './inline-response-200-hydra-search-hydra-mapping';


export interface InlineResponse200HydraSearch { 
    type?: string;
    'hydra:template'?: string;
    'hydra:variableRepresentation'?: string;
    'hydra:mapping'?: Array<InlineResponse200HydraSearchHydraMapping>;
}

