/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {UserJsonldLightRead} from "./user-jsonld-light-read";


export interface OrderJsonldLightRead {
    readonly '@id'?: string;
    readonly '@type'?: string;
    readonly id?: number;
    createdAt?: string;
    price?: number;
    user?: UserJsonldLightRead | null;
}

