/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Collection } from './collection';


export interface Order { 
    readonly id?: number;
    createdAt?: string;
    price?: number;
    weight?: number | null;
    user?: string | null;
    endAt?: string | null;
    isValidate?: boolean | null;
    status?: string;
    addresses?: Collection;
}

