/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PictureJsonld } from './picture-jsonld';


export interface ProductJsonld { 
    readonly '@context?': string | any | null;
    readonly '@id'?: string;
    readonly '@type'?: string;
    readonly id?: number;
    ean?: string;
    title?: string;
    description?: string | null;
    createdAt?: string;
    picture?: string | null;
    stock?: number | null;
    price?: number | null;
    category?: string | null;
    pictures?: Array<PictureJsonld>;
    brand?: string | null;
    isActive?: boolean;
}

